/*
 * This file was last modified at 2024-03-18 11:54 by Victor N. Skurikhin.
 * mock_storage.go
 * $Id$
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorage) Get(name string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", name)
	ret0, _ := ret[0].(*string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStorage)(nil).Get), name)
}

// Put mocks base method.
func (m *MockStorage) Put(name string, value *string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", name, value)
}

// Put indicates an expected call of Put.
func (mr *MockStorageMockRecorder) Put(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStorage)(nil).Put), name, value)
}

// ReadFromFile mocks base method.
func (m *MockStorage) ReadFromFile(fileName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReadFromFile", fileName)
}

// ReadFromFile indicates an expected call of ReadFromFile.
func (mr *MockStorageMockRecorder) ReadFromFile(fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFromFile", reflect.TypeOf((*MockStorage)(nil).ReadFromFile), fileName)
}

// SaveToFile mocks base method.
func (m *MockStorage) SaveToFile(fileName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveToFile", fileName)
}

// SaveToFile indicates an expected call of SaveToFile.
func (mr *MockStorageMockRecorder) SaveToFile(fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToFile", reflect.TypeOf((*MockStorage)(nil).SaveToFile), fileName)
}
