/*
 * This file was last modified at 2024-07-08 13:46 by Victor N. Skurikhin.
 * json_server_config_easyjson.go
 * $Id$
 */

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package env

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF30d2885DecodeGithubComVskurikhinGometricsInternalEnv(in *jlexer.Lexer, out *serverConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = string(in.String())
		case "crypto_key":
			out.CryptoKey = string(in.String())
		case "database_dsn":
			out.DatabaseDSN = string(in.String())
		case "grpc_address":
			out.GRPCAddress = string(in.String())
		case "restore":
			out.Restore = bool(in.Bool())
		case "store_file":
			out.StoreFile = string(in.String())
		case "store_interval":
			out.StoreInterval = string(in.String())
		case "trusted_subnet":
			out.TrustedSubnet = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF30d2885EncodeGithubComVskurikhinGometricsInternalEnv(out *jwriter.Writer, in serverConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		out.String(string(in.CryptoKey))
	}
	{
		const prefix string = ",\"database_dsn\":"
		out.RawString(prefix)
		out.String(string(in.DatabaseDSN))
	}
	{
		const prefix string = ",\"grpc_address\":"
		out.RawString(prefix)
		out.String(string(in.GRPCAddress))
	}
	{
		const prefix string = ",\"restore\":"
		out.RawString(prefix)
		out.Bool(bool(in.Restore))
	}
	{
		const prefix string = ",\"store_file\":"
		out.RawString(prefix)
		out.String(string(in.StoreFile))
	}
	{
		const prefix string = ",\"store_interval\":"
		out.RawString(prefix)
		out.String(string(in.StoreInterval))
	}
	{
		const prefix string = ",\"trusted_subnet\":"
		out.RawString(prefix)
		out.String(string(in.TrustedSubnet))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v serverConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF30d2885EncodeGithubComVskurikhinGometricsInternalEnv(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v serverConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF30d2885EncodeGithubComVskurikhinGometricsInternalEnv(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *serverConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF30d2885DecodeGithubComVskurikhinGometricsInternalEnv(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *serverConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF30d2885DecodeGithubComVskurikhinGometricsInternalEnv(l, v)
}
