/*
 * This file was last modified at 2024-07-08 13:46 by Victor N. Skurikhin.
 * json_agent_config_easyjson.go
 * $Id$
 */

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package env

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9b168d43DecodeGithubComVskurikhinGometricsInternalEnv(in *jlexer.Lexer, out *agentConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = string(in.String())
		case "crypto_key":
			out.CryptoKey = string(in.String())
		case "grpc_address":
			out.GRPCAddress = string(in.String())
		case "poll_interval":
			out.PollInterval = string(in.String())
		case "report_interval":
			out.ReportInterval = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9b168d43EncodeGithubComVskurikhinGometricsInternalEnv(out *jwriter.Writer, in agentConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		out.String(string(in.CryptoKey))
	}
	{
		const prefix string = ",\"grpc_address\":"
		out.RawString(prefix)
		out.String(string(in.GRPCAddress))
	}
	{
		const prefix string = ",\"poll_interval\":"
		out.RawString(prefix)
		out.String(string(in.PollInterval))
	}
	{
		const prefix string = ",\"report_interval\":"
		out.RawString(prefix)
		out.String(string(in.ReportInterval))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v agentConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9b168d43EncodeGithubComVskurikhinGometricsInternalEnv(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v agentConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9b168d43EncodeGithubComVskurikhinGometricsInternalEnv(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *agentConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9b168d43DecodeGithubComVskurikhinGometricsInternalEnv(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *agentConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9b168d43DecodeGithubComVskurikhinGometricsInternalEnv(l, v)
}
